language: en_US
debug: false

combat:
  duration: 20s
  command_block_mode: "blacklist"
  blocked_commands:
    - "logout"
    - "tpa"
    - "tpahere"
    - "afk"
    - "spawn"
    - "tpaccept"
    - "tpacancel"
    - "rtp"
    - "warp"
    - "home"
    - "team"
    - "enderchest"
    - "ec"
    - "vanish"
    - "v"
  allowed_commands:
    - "msg"
    - "r"
    - "reply"
    - "tell"
    - "w"
    - "whisper"
    - "shop"
    - "buy"
    - "sell"
    - "ah"
  exempt_admin_kick: true
  disable_flight: false
  item_restrictions:
    enabled: false
    disabled_items:
      - CHORUS_FRUIT
      - ELYTRA

worlds:
  blacklisted_worlds:
    - duels-1
    - duels-2
    - duels-3
    - duels-4

enderpearl:
  refresh_combat_on_land: false

enderpearl_cooldown:
  enabled: true
  duration: 10s
  in_combat_only: true
  worlds:
    minigames: false

trident:
  refresh_combat_on_land: false
  banned_worlds:
    world_nether: true

trident_cooldown:
  enabled: true
  duration: "10s"
  in_combat_only: true
  worlds:
    world: true
    world_nether: false
    world_the_end: true

death_animation:
  enabled: true
  only_player_kill: true
  animation:
    lightning: true
    fire_particles: true

kill_rewards:
  enabled: true
  commands:
    - "donutcratecore shards give %killer% 10"
  cooldown:
    use_global_cooldown: false
    duration: 1d
    use_same_player_cooldown: true
    same_player_duration: 1d

newbie_protection:
  enabled: true
  duration: 10m
  protect_from_pvp: true
  protect_from_mobs: false
  remove_on_damage_dealt: true
  display:
    use_bossbar: true
    use_actionbar: false
    bossbar:
      title: "&#4CAF50PvP Protection: &#FFFFFF%time%"
      color: "GREEN"
      style: "SOLID"
  worlds:
    world: true
    world_nether: false
    world_the_end: false

safezone_protection:
  enabled: true
  barrier_material: "RED_STAINED_GLASS"
  barrier_detection_radius: 5
  barrier_height: 3
  push_back_force: 0.6
  worlds:
    spawn_world: true
    world: true
    world_nether: false
    world_the_end: false

claim_protection:
  enabled: false
  barrier_material: "BLUE_STAINED_GLASS"
  barrier_detection_radius: 5
  barrier_height: 3
  push_back_force: 0.6
  required_permission: BUILD
  worlds:
    world: true
    world_nether: true
    world_the_end: false